### ISSUE TITLE
NISRA Harvester: Frequency and contact name

### ISSUE THREAD

**Issue by SusanBot85** [datopian/ckanext-opendatani#31]
for Frequency and contact name

this already applied with a fixed value (`OSNI Mapping Helpdesk`) this follow the same pattern they use for their other DCAT harvester we have. 

https://github.com/datopian/ckanext-opendatani/pull/29/files#:~:text=else%20%27Updated%27-,package_dict,-%5B%27frequency%27

but for a reason is not getting reflected, so thats a bug to look into. 

So for fast feeback i will update this manually so we can send message to the client. and if they approve of it, fixing the bug and other udpate will be part of the main work

_Originally posted by @steveoni in https://github.com/datopian/ckanext-opendatani/issues/28#issuecomment-1978436877_

**Comment by steveoni** [comment]
@SusanBot85 this is now resolved. 

you can see the result here https://ni.dev.datopian.com/dataset/ccmlgd/resource/11d6bc4e-1112-4603-89ad-3bbf5fa78b5d

and also here are the list of harvested data
https://ni.dev.datopian.com/harvest
